export const initialData = [
    { name: 'Anas',chat:['hy','heloo','how are you' , 'fine ' ,'what about you', 'iam good' , 'thanks for asking' ,'didi you dring tea' , 'yes of coursw'] ,line:'online' ,line:'online'},
    { name: 'ravi',chat:['hy','heloo','how are you' , 'fine ' ,'what about you', 'iam good' , 'thanks for asking' ,'didi you dring tea' , 'yes of coursw'] ,line:'ofline'  },
    { name: 'haro',chat:['hy','heloo','how are you' , 'fine ' ,'what about you', 'iam good' , 'thanks for asking' ,'didi you dring tea' , 'yes of coursw'] ,line:'ofline'  },
    { name: 'anub',chat:['hy','heloo','how are you' , 'fine ' ,'what about you', 'iam good' , 'thanks for asking' ,'didi you dring tea' , 'yes of coursw'] ,line:'ofline'  },
    { name: 'karthu',chat:['hy','heloo','how are you' , 'fine ' ,'what about you', 'iam good' , 'thanks for asking' ,'didi you dring tea' , 'yes of coursw '] ,line:'online' },
    { name: 'moosa',chat:['hy','heloo','how are you' , 'fine ' ,'what about you', 'iam good' , 'thanks for asking' ,'didi you dring tea' , 'yes of coursw'] ,line:'online' },
    { name: 'abdu',chat:['hy','heloo','how are you' , 'fine ' ,'what about you', 'iam good' , 'thanks for asking' ,'didi you dring tea' , 'yes of coursw'] ,line:'online'  },
    { name: 'chndrika',chat:['hy','heloo','how are you' , 'fine ' ,'what about you', 'iam good' , 'thanks for asking' ,'didi you dring tea' , 'yes of cour sw'] ,line:'online' },
    { name: 'kanishka',chat:['hy','heloo','how are you' , 'fine ' ,'what about you', 'iam good' , 'thanks for asking' ,'didi you dring tea' , 'yes of cour sw'] ,line:'online' },
    { name: 'rsulu',chat:['hy','heloo','how are you' , 'fine ' ,'what about you', 'iam good' , 'thanks for asking' ,'didi you dring tea' , 'yes of coursw'] ,line:'online' },
    { name: 'bibi mwone',chat:['hy','heloo','how are you' , 'fine ' ,'what about you', 'iam good' , 'thanks for asking' ,'didi you dring tea' , 'yes of co ursw'] ,line:'online' },
    { name: 'sanessh',chat:['hy','heloo','how are you' , 'fine ' ,'what about you', 'iam good' , 'thanks for asking' ,'didi you dring tea' , 'yes of cours w'] ,line:'ofline' },
    { name: ' krishnan',chat:['hy','heloo','how are you' , 'fine ' ,'what about you', 'iam good' , 'thanks for asking' ,'didi you dring tea' , 'yes of cou rsw'] ,line:'online' },
    { name: 'sulaiman',chat:['hy','heloo','how are you' , 'fine ' ,'what about you', 'iam good' , 'thanks for asking' ,'didi you dring tea' , 'yes of cour sw'] ,line:'online' },
    { name: 'kimichii',chat:['hy','heloo','how are you' , 'fine ' ,'what about you', 'iam good' , 'thanks for asking' ,'didi you dring tea' , 'yes of cour sw'] ,line:'online' },
    { name: 'janu',chat:['hy','heloo','how are you' , 'fine ' ,'what about you', 'iam good' , 'thanks for asking' ,'didi you dring tea' , 'yes of coursw'] ,line:'online'  },
    { name: 'kabeer',chat:['hy','heloo','how are you' , 'fine ' ,'what about you', 'iam good' , 'thanks for asking' ,'didi you dring tea' , 'yes of coursw '] ,line:'ofline' },
    { name: 'abas',chat:['hy','heloo','how are you' , 'fine ' ,'what about you', 'iam good' , 'thanks for asking' ,'didi you dring tea' , 'yes of coursw'] ,line:'ofline'  },
    { name: 'vinod',chat:['hy','heloo','how are you' , 'fine ' ,'what about you', 'iam good' , 'thanks for asking' ,'didi you dring tea' , 'yes of coursw'] ,line:'online' },
    { name: 'mani kndan',chat:['hy','heloo','how are you' , 'fine ' ,'what about you', 'iam good' , 'thanks for asking' ,'didi you dring tea' , 'yes of co ursw'] ,line:'online' },
    { name: 'kobalan',chat:['hy','heloo','how are you' , 'fine ' ,'what about you', 'iam good' , 'thanks for asking' ,'didi you dring tea' , 'yes of cours w'] ,line:'online' },
    { name: 'pp sashi',chat:['hy','heloo','how are you' , 'fine ' ,'what about you', 'iam good' , 'thanks for asking' ,'didi you dring tea' , 'yes of cour sw'] ,line:'online' },
  ];